apiVersion: apps/v1
kind: Deployment
metadata:
  name:  orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: alamindocker/orders
          env:
            - name: NATS_URL
              value: 'http://nats-clusterip-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
---
apiVersion: v1
kind: Service
metadata:
  name:  orders-clusterip-srv
spec:
  selector:
    app:  orders
  ports:
  - name:  orders
    port:  3005
    targetPort:  3005